from _typeshed import Incomplete
from requests import PreparedRequest as PreparedRequest
from requests.auth import AuthBase

class TokenAuth(AuthBase):
    token: Incomplete
    def __init__(self, token: str) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __call__(self, req: PreparedRequest) -> PreparedRequest: ...
