# action.yaml
name: 'Get release version'
description: 'A GitHub Action to determine the next version by checking the commit history for Conventional Commits'
inputs:
  suffix:
    description: 'The suffix to add to the version'
    required: false
    default: ""
  only-increase-suffix:
    description: 'Only increases the suffix increment, when any change got detected'
    required: true
    default: false
outputs:
  version:
    description: 'The versoon to use'
    value: ${{ steps.get-square.outputs.num_squared }}
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash    
    - name: Fetch the number's square
      id: get-square
      run: python app.py
      shell: bash
