# action.yaml
name: "Get release version"
description: "A GitHub Action to determine the next version by checking the commit history for Conventional Commits"
inputs:
  suffix:
    description: "The suffix to add to the version"
    required: false
    default: "hotfix"
  create-tag:
    description: "Create a Git Tag for the version"
    required: false
    default: "false"
  only-increase-suffix:
    description: "Only increases the suffix increment, when any change got detected"
    required: true
    default: "false"
outputs:
  version:
    description: "The version to use"
  has-changes:
    description: "Determines, if changes got detected, which require a version change according to Conventional Commits."
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - --only-increase-suffix
    - ${{ inputs.only-increase-suffix }}
    - --suffix
    - ${{ inputs.suffix }}
    - --create-tag
    - ${{ inputs.create-tag }}
