# action.yaml
name: "Get release version"
description: "A GitHub Action to determine the next version by checking the commit history for Conventional Commits"
inputs:
  prefix:
    description: "The prefix that should be prepended to the version."
    required: false
    default: "v"
  suffix:
    description: "The suffix that should appended to the version."
    required: false
    default: "NONE"
  previous-version-suffix:
    description: "The suffix that should be replaced with the value in `suffix`."
    required: false
    default: "NONE"
  bumping-suffix:
    description: "The suffix to append to the version (or increment if it already exists) if `only-bump-suffix` is `true`."
    required: false
    default: "hotfix"
  only-bump-suffix:
    description: "Bump the `bumping-suffix` instead of the version if changes were detected."
    required: false
    default: "false"
  create-tag:
    description: "Create a Git Tag for the version and push it if a remote is configured."
    required: false
    default: "true"
  mode:
    description: "The mode to use for determining the next version. Possible values: `semantic`, `hash-based`."
    required: false
    default: "semantic"
outputs:
  version:
    description: "The next version, without the prefix"
  version-name:
    description: "The next version, with the prefix"
  previous-version:
    description: "The previous version, without the prefix"
  previous-version-name:
    description: "The previous version, with the prefix"
  has-changes:
    description: "If any relevant changes got detected"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - --prefix
    - ${{ inputs.prefix }}
    - --suffix
    - ${{ inputs.suffix }}
    - --previous-version-suffix
    - ${{ inputs.previous-version-suffix }}
    - --bumping-suffix
    - ${{ inputs.bumping-suffix }}
    - --only-bump-suffix
    - ${{ inputs.only-bump-suffix }}
    - --create-tag
    - ${{ inputs.create-tag }}
    - --mode
    - ${{ inputs.mode }}
