# action.yaml
name: 'Get release version'
description: 'A GitHub Action to determine the next version by checking the commit history for Conventional Commits'
inputs:
  suffix:
    description: 'The suffix to add to the version'
    required: false
    default: ""
  only-increase-suffix:
    description: 'Only increases the suffix increment, when any change got detected'
    required: true
    default: false
outputs:
  version:
    description: 'The version to use'
    value: ${{ steps.determine-version.outputs.version }}
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash

    - name: Download get-next-version
      shell: bash
      run: |
        wget -O /usr/bin/get-next-version https://github.com/thenativeweb/get-next-version/releases/download/2.6.1/get-next-version-darwin-amd64
        chmod +x /usr/bin/get-next-version

    - name: Determine the version
      id: determine-version
      run: python app.py --only-increase-suffix ${{ inputs.only-increase-suffix }} --suffix ${{ inputs.suffix }}
      shell: bash
