# action.yaml
name: "Get release version"
description: "A GitHub Action to determine the next version by checking the commit history for Conventional Commits"
inputs:
  prefix:
    description: "The prefix that should be prepended to the version"
    required: false
    default: "v"
  suffix:
    description: "The suffix that should be incremented / appended to the version"
    required: false
    default: "hotfix"
  only-increase-suffix:
    description: "Increment the suffix if any changes got detected"
    required: false
    default: "false"
  only-replace-suffix-with:
    description: "Don't increment the version, only replace the suffix in `suffix` with the suffix from this input. `create-tag` and `prefix` still work with this option."
    required: false
    default: "false"
  create-tag:
    description: "Create a Git Tag for the version and push it if a remote is configured"
    required: false
    default: "true"
outputs:
  version:
    description: "The next version, without the prefix"
  version-name:
    description: "The next version, with the prefix"
  has-changes:
    description: "If any relevant changes got detected"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - --only-increase-suffix
    - ${{ inputs.only-increase-suffix }}
    - --suffix
    - ${{ inputs.suffix }}
    - --create-tag
    - ${{ inputs.create-tag }}
    - --prefix
    - ${{ inputs.prefix }}
    - --only-replace-suffix-with
    - ${{ inputs.only-replace-suffix-with }}
