# action.yaml
name: "Get release version"
description: "A GitHub Action to determine the next version by checking the commit history for Conventional Commits"
inputs:
  prefix:
    description: "The prefix that should be prepended to the version."
    required: false
    default: "v"
  suffix:
    description: "The suffix that should appended to the version.  Use `NONE` for no suffix."
    required: false
    default: "NONE"
  reference-version-suffix:
    description: "The suffix that should be replaced with the value in `suffix`.  Use `NONE` for no suffix."
    required: false
    default: "NONE"
  bumping-suffix:
    description: "The suffix to append to the version (or increment if it already exists) if `only-bump-suffix` is `true`."
    required: false
    default: "hotfix"
  only-bump-suffix:
    description: "Bump the `bumping-suffix` instead of the version if changes were detected."
    required: false
    default: "false"
  create-tag:
    description: "Create a Git Tag for the version and push it if a remote is configured."
    required: false
    default: "true"
  git-username:
    description: "The username for creating the (annotated) git tag. Use `NONE` for no username."
    required: false
    default: "NONE"
  git-email:
    description: "The email address for creating the (annotated) git tag. Use `NONE` for no email address."
    required: false
    default: "NONE"
  mode:
    description: "The mode to use for determining the next version. Possible values: `semantic`, `hash-based`."
    required: false
    default: "semantic"
outputs:
  version:
    description: "The next version, without the prefix"
  version-name:
    description: "The next version, with the prefix"
  previous-version:
    description: "The previous version, without the prefix"
  previous-version-name:
    description: "The previous version, with the prefix"
  tag-created:
    description: "If any relevant changes got detected and a tag got created."
runs:
  using: "docker"
  image: "docker://ghcr.io/wemogy/get-release-version-action:4.2.2"
  args:
    - --prefix
    - ${{ inputs.prefix }}
    - --suffix
    - ${{ inputs.suffix }}
    - --reference-version-suffix
    - ${{ inputs.reference-version-suffix }}
    - --bumping-suffix
    - ${{ inputs.bumping-suffix }}
    - --only-bump-suffix
    - ${{ inputs.only-bump-suffix }}
    - --create-tag
    - ${{ inputs.create-tag }}
    - --git-username
    - ${{ inputs.git-username }}
    - --git-email
    - ${{ inputs.git-email }}
    - --mode
    - ${{ inputs.mode }}
