[project]
name = "get-release-version-action"
version = "0.1.0"
classifiers = ["Private :: Do Not Upload"]
requires-python = ">=3.13"
dependencies = [
    "gitpython>=3.1.44",
    "python-semantic-release==9.5.0",
    "pyyaml>=6.0.2",
    "semver>=3.0.4",
]

[project.scripts]
get-release-version-action = "get_release_version_action:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "assertpy>=1.1",
    "mypy>=1.15.0",
    "pytest>=8.3.4",
    "ruff>=0.9.6",
    "types-assertpy>=1.1.0.20240712",
    "types-pyyaml>=6.0.12.20241230",
]

[tool.ruff]
line-length = 150
exclude = [
    ".mypy_stubs"
]

[tool.ruff.lint]
select = ["ALL"]
unfixable = [
    "ERA001", # Commented out code
]
ignore = [
    "D203",   # Would put a blank line before class docstrings
    "D212",   # Would put the summary on the same line as the docstring qoutes
    "COM812", # Conflicts with formatter
    "FIX002", # Prevents TODO comments
    "TD002",  # Prevents authorless TODO comments
]
flake8-quotes.inline-quotes="single"

[tool.ruff.format]
quote-style = "single"
docstring-code-format = true

[tool.mypy]
mypy_path = ".mypy_stubs"
strict = true
