name: "Containers"
description: "Builds and optionally pushes container images"

inputs:
  container-registry-server:
    description: "Container registry server"
    default: "docker.io"
    required: false
  container-registry-username:
    description: "Container registry username"
    required: false
  container-registry-password:
    description: "Container registry password"
    required: false
  version:
    description: "The version of the container image"
    required: true
  push:
    description: "Whether to push the container image to the registry"
    required: true
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Login to Azure Container Registry
      if: inputs.push == 'true'
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.container-registry-server }}
        username: ${{ inputs.container-registry-username }}
        password: ${{ inputs.container-registry-password }}

    - name: Build and push Container image
      uses: docker/build-push-action@v5
      with:
        build-args: |
          VERSION=${{ inputs.version }}
        file: Dockerfile
        push: ${{ inputs.push }}
        tags: ${{ inputs.container-registry-server }}/get-release-version-action:${{ inputs.version }}
