from jinja2 import Environment as Environment
from pathlib import Path
from semantic_release.changelog.release_history import Release as Release
from semantic_release.version import Version as Version

def get_release_notes_template(template_dir: Path) -> str: ...
def render_default_changelog_file(template_environment: Environment) -> str: ...
def render_release_notes(release_notes_template: str, template_environment: Environment, version: Version, release: Release) -> str: ...
