from _typeshed import Incomplete
from semantic_release.version import Version as Version

log: Incomplete

class VersionGitHubActionsOutput:
    OUTPUT_ENV_VAR: str
    def __init__(self, released: bool | None = None, version: Version | None = None) -> None: ...
    @property
    def released(self) -> bool | None: ...
    @released.setter
    def released(self, value: bool) -> None: ...
    @property
    def version(self) -> Version | None: ...
    @version.setter
    def version(self, value: Version) -> None: ...
    @property
    def tag(self) -> str | None: ...
    def to_output_text(self) -> str: ...
    def write_if_possible(self, filename: str | None = None) -> None: ...
