from _typeshed import Incomplete
from pathlib import Path
from semantic_release.errors import InvalidConfiguration as InvalidConfiguration
from typing import Any

log: Incomplete

def rprint(msg: str) -> None: ...
def noop_report(msg: str) -> None: ...
def indented(msg: str, prefix: str = ...) -> str: ...
def parse_toml(raw_text: str) -> dict[Any, Any]: ...
def load_raw_config_file(config_file: Path | str) -> dict[Any, Any]: ...
