name: Setup Python
description: Setup python
runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version-file: pyproject.toml
        cache: "poetry"

    - name: Install poetry
      uses: abatilo/actions-poetry@v3

    - name: Install dependencies
      run: poetry install --no-root --no-interaction --with dev
      shell: bash
