class SemanticReleaseBaseError(Exception): ...
class InvalidConfiguration(SemanticReleaseBaseError): ...
class InvalidVersion(ValueError, SemanticReleaseBaseError): ...
class NotAReleaseBranch(InvalidConfiguration): ...
class CommitParseError(SemanticReleaseBaseError): ...
class MissingMergeBaseError(SemanticReleaseBaseError): ...
