version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: '[%(levelname)s | %(name)s] %(message)s'
handlers:
  stdout:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: app.log
    maxBytes: 10000
    backupCount: 0
loggers:
  root:
    level: DEBUG
    handlers:
      - stdout
      - file
