name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.CHECKOUT_TOKEN  }}
          fetch-depth: 0
      # Determine Release Version
      - name: Run
        id: get-release-version
        uses: ./
        with:
          create-tag: "true"

      - name: Show the next version
        run: |
          echo ${{ steps.get-release-version.outputs.version }}
          echo ${{ steps.get-release-version.outputs.has-changes }}

      # Create GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: steps.get-release-version.outputs.has-changes == 'true'
        with:
          tag_name: ${{ steps.get-release-version.outputs.version }}
          name: Version ${{ steps.get-release-version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
