name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.CHECKOUT_TOKEN  }}
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Get version for next release
        id: get-release-version
        uses: ./
        with:
          create-tag: "true"
          use-local-container: "true"

      - uses: actions/checkout@v2
      - name: Build Containers
        uses: ./.github/actions/containers
        with:
          container-registry-server: ${{ secrets.CONTAINER_REGISTRY_LOGIN_SERVER }}
          container-registry-username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          container-registry-password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
          version: ${{ steps.get-release-version.outputs.version }}
          push: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: steps.get-release-version.outputs.tag-created == 'true'
        with:
          tag_name: ${{ steps.get-release-version.outputs.version-name }}
          name: Version ${{ steps.get-release-version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
