name: Test Action
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: Test the action
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run the action
        id: get-release-version
        uses: ./.github/actions/local-action
        with:
          create-tag: "false"

      - name: Print the outputs
        run: |
          echo "version=${{ steps.get-release-version.outputs.version }}"
          echo "version-name=${{ steps.get-release-version.outputs.version-name }}"
          echo "previous-version=${{ steps.get-release-version.outputs.previous-version }}"
          echo "previous-version-name=${{ steps.get-release-version.outputs.previous-version-name }}"
          echo "tag-created=${{ steps.get-release-version.outputs.tag-created }}"

  run-tests:
    runs-on: ubuntu-latest
    name: Run E2E Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: ./.github/actions/setup-python

      - name: Setup git
        run: |
          git config --global user.email "it@wemogy.com"
          git config --global user.name "Wemogy IT"

      - name: Run pytest
        run: poetry run pytest --junit-xml test-result.xml tests/e2e

      - name: Upload test results
        if: always()
        uses: pmeier/pytest-results-action@v0.6.0
        with:
          path: test-result.xml
          summary: true
          display-options: fEX
          fail-on-empty: true
          title: E2E Test Results
