name: Test Action
on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test the action
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # [X] https://github.com/actions/checkout/issues/1471
      # [X] https://github.com/actions/checkout/pull/579#issuecomment-1615799806
      # [ ] https://github.com/actions/checkout/issues/206
      - name: Fetch tags
        run: git fetch --prune --unshallow --tags

      - name: Show git log
        run: |
          git fetch --prune --unshallow --tags
          echo $(git describe --tags)
          echo $(git --no-pager tag -l)
          echo $(git log --tags)

      - name: Run
        id: get-release-version
        uses: ./

      - name: Show the next version
        run: |
          echo ${{ steps.get-release-version.outputs.version }}
          echo ${{ steps.get-release-version.outputs.has-changes }}
